### ISSUE TITLE
Add raw data without upload to Github

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#1]
I will add a folder within raw that includes the data and a script that parses the relevant csv-files from the subfolders. The raw data will not be uploaded to Github so that we don't bloat the repository (as discussed with xrotwang).

This will only be done for the languages that do not have a ND-tag.

**Comment by xrotwang** [comment]
ND clause for audio only is fine, though.

**Comment by FredericBlum** [comment]
I added a script to parse all zip-files in the directory. I create raw-files for the phone, and the word-corpus, as well as another file with the glossing conventions, and a file with all the speaker/file-metadata that I parse as discussed in #5

**Comment by FredericBlum** [comment]
So I think we can close this issue, or is there anything else that we will not do through #4 ?
