### ISSUE TITLE
Add ExampleTable

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#11]
Copying from #8:

- adding an ExampleTable, i.e. aggregating the DoReCo data on sentence level into - ideally glossed - IGT sentences

@xrotwang The information whether each file is glossed is also part of `metadata.csv`

**Comment by xrotwang** [comment]
See https://github.com/cldf-datasets/doreco/blob/ac227b3f466612ea64e7d0dca9d92182e2954a18/cldfbench_doreco.py#L323-L336
