### ISSUE TITLE
Add MediaTable

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#12]
Copying from #8:

- to add a MediaTable linking the lexical data to the audio files.

@xrotwang Quite lost on how we would proceed to implement this. Is this something you will take charge of?

**Comment by xrotwang** [comment]
See https://github.com/cldf-datasets/doreco/blob/ac227b3f466612ea64e7d0dca9d92182e2954a18/cldfbench_doreco.py#L221-L241
