### ISSUE TITLE
SQlite Tutorial: Storing the query and running termgraph

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#15]
In the last steps of the sqlite tutorial, I am trying to reproduce the termgraph, but running to an error.

I store the output as this:

```
sqlite> .output sr_by_lang.sql
sqlite> SELECT
   ...>     w.cldf_languagereference,
   ...>     AVG(u.speech_rate) AS sr
   ...> FROM
   ...>     utterance_initials AS ui,
   ...>     'words.csv' AS w,
   ...>     utterances AS u
   ...> WHERE 
   ...>     u.u_id = ui.u_id AND ui.wd_id = w.cldf_id 
   ...> GROUP BY w.cldf_languagereference 
   ...> ORDER BY sr;
sqlite> .output
sqlite> .quit
```

But when I run the command as indicated, I run into the following problem:

```
(doreco) blum@lingn45 doreco % sqlite3 -csv doreco.sqlite < sr_by_lang.sql | termgraph
Parse error near line 1: near "kama1351": syntax error
  kama1351|8.50360541282399 nngg1234|9.4337050500625 lowe1385|9.49056660765644 t
  ^--- error here

Traceback (most recent call last):
  File "/Users/blum/Projects/venv/doreco/bin/termgraph", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/blum/Projects/venv/doreco/lib/python3.11/site-packages/termgraph/termgraph.py", line 133, in main
    _, labels, data, colors = read_data(args)
                              ^^^^^^^^^^^^^^^
  File "/Users/blum/Projects/venv/doreco/lib/python3.11/site-packages/termgraph/termgraph.py", line 712, in read_data
    colors = check_data(labels, data, args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/blum/Projects/venv/doreco/lib/python3.11/site-packages/termgraph/termgraph.py", line 569, in check_data
    len_categories = len(data[0])
                         ~~~~^^^
IndexError: list index out of range
```

@xrotwang Is there something wrong with the way I store the query output? How should it be done correctly?

**Comment by xrotwang** [comment]
The `-csv` option used for the query in the tutorial forces CSV-like output:
```
$ sqlite3 -csv doreco.sqlite < sr_by_lang.sql
kama1351,8.50360541282399
nngg1234,9.4337050500625
lowe1385,9.49056660765644
trin1278,10.1543779066867
yong1270,10.2089764549355
resi1247,10.448910686496
sadu1234,10.5393271962571
arap1274,10.92203496636
```
which can be piped right into `termgraph`. The same effect can be obtained using
```sql
> .mode csv
```
in an interactive sqlite session.

**Comment by FredericBlum** [comment]
Not sure I am understanding you right. My output looks as follows:

```
kama1351,8.50360541282399
nngg1234,9.4337050500625
lowe1385,9.49056660765644
trin1278,10.1543779066867
...
```

But despite the `-csv` option, I receive an error:

```
(doreco) blum@lingn45 doreco % sqlite3 -csv doreco.sqlite < sr_by_lang.sql
Parse error near line 1: near "kama1351": syntax error
  kama1351,8.50360541282399 nngg1234,9.4337050500625 lowe1385,9.49056660765644 t
  ^--- error here
```

**Comment by xrotwang** [comment]
Ah, sorry, I misunderstood the issue. The tutorial asks to store the actual SQL query as `sr_by_lang.sql`, **not its result**.

**Comment by FredericBlum** [comment]
Maybe this step could be added to the tutorial? This would probably make it easier for newcomers to SQlite to see how such queries or their results can be stored, e.g. in csv-tables or similar. Of course one could look at other tutorials, but it would be handy to take them by their hand and lead them through all the details.

**Comment by xrotwang** [comment]
Yes, the tutorial isn't overly long right now, so we should add more detail (and/or link to exact documentation elsewhere). So what we should describe in the tutorial is
- running SQL in SQLite's repl interactively
- storing interactive results
- running SQL from files

**Comment by FredericBlum** [comment]
It could be a good practice task for me to implement that. If you agree, I would open a PR and work on this a bit until the end of May. Then you give it a check?

**Comment by xrotwang** [comment]
> It could be a good practice task for me to implement that. If you agree, I would open a PR and work on this a bit until the end of May. Then you give it a check?

Sure! "Write the documentation you would have wanted to read" is my approach to docs anyway :)
