### ISSUE TITLE
Run query

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#23]
@xrotwang Not working with the database makes me lose all knowledge, it seems. In a PR, you described that you run the query with the following command:

`time cldfbench doreco.query --format tsv init_query.sql > res.tsv`

However, I only get a cldfbench error message that the command is invalid. How do I have to adapt the command so that the query runs correctly?

**Comment by FredericBlum** [comment]
If I run `sqlite3 -csv doreco.sqlite < init_query.sql`, I get a "no such function: STDEV` error again, which is frustrating...

**Comment by xrotwang** [comment]
You need to make the `doreco.query` subcommand known to `cldfbench`. This works via [entry points](https://setuptools.pypa.io/en/latest/userguide/entry_point.html), i.e. package metadata that is available to other python packages **after installation**. I.e. you need to install the doreco dataset running `pip install -e .` to make `cldfbench` aware of the custom dataset functonality.
See https://github.com/cldf/cldfbench/blob/master/src/cldfbench/commands/README.md

**Comment by FredericBlum** [comment]
Thank you! I should have realized that this was a custom command I can install... thanks for the very quick help

**Comment by xrotwang** [comment]
> Not working with the database makes me lose all knowledge, it seems.

Having a lot of tools at your disposal and being familiar with each one is hard to achieve. I still hope that CLDF is not only my own personal way to make the same tools applicable to a lot more data than before :)
