### ISSUE TITLE
X-Sampa to CLTS

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#3]
For the transcription, all phones are currently in X-Sampa and need to be transfered to CLTS.

**Comment by FredericBlum** [comment]
@Lingulist You mentioned something about extracting concordances for this conversion, but I am not sure what you are referring to. Could you elaborate briefly?

**Comment by LinguList** [comment]
I recommend reading our paper, List, Sims, Forkel 2020 on IGT for this purpose, where we mention this (Robert has developed tge package further by now).

**Comment by xrotwang** [comment]
`pyigt` can be used to extract word/morpheme concordances, not phoneme concordances. So I don't think it's relevant for X-Sampa to CLTS conversion.

**Comment by LinguList** [comment]
It depends on the corpus structure, I thought, we first get a concordance of words and then convert those to clts/bipa, with the typical orthoprofile procedure from pylexibank. Here, you woukd use a concordance to get those lexemes, right?

**Comment by LinguList** [comment]
But if that is not the case, one needs to use segments directly, which changes the procedure of applying the profile.

**Comment by xrotwang** [comment]
Ah, ok. Yes, one could do that - although I wouldn't want to bring in all the pylexibank machinery in this repos. So maybe we should
- create these concordances
- put them in a doreco-lexibank repos
- work on orthography profiles there

Then, copy the profiles back here and add the CLTS conversion to the makecldf command.

**Comment by LinguList** [comment]
Yes, sounds like a plan. We have a rather complete sampa profile. Need to look that up when I find time. It may be in the orthograpy repo...

**Comment by LinguList** [comment]
It is https://github.com/orthograpy/orthograpy, if I am not mistaken.

**Comment by xrotwang** [comment]
See https://github.com/cldf-datasets/doreco/blob/main/etc/orthography.tsv
