### ISSUE TITLE
Parameters that exist twice

### ISSUE THREAD

**Issue by chrzyki** [cldf-datasets/doreco#30]
The following parameters exist twice in `ParameterTable`:

- `a` (id: `1`, `339`)
- `dz` (id: `53`, `88`)
- `nʲ` (id: `126`, `311`)
- `ʉː` (id: `130`, `237`)

`dz` e.g. is used 5027 times with id `53` and 1446 times with id `88`. I think that depending on how these values are used for counts/frequencies, this might affect the overall results of parameter counts etc.?

**Comment by xrotwang** [comment]
It probably doesn't affect the analysis, because the CLTS data joined via ParameterTable is only used to filter phones by feature/sound class.
