### ISSUE TITLE
Metadata: Core vs. extended, speakers

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#5]
@xrotwang The core set contains all the data that is time-aligned, while the extended set also includes the files that have morphological segmentation but no time alignment. We have two options:

1) We only include the data with time-alignment
2) We include all data and include a look-up in the language-specific metadata files to tag the files that are part of the extended set.

There is also several other metadata like speaker age, date of recording, and sound quality. Where do we store this information? Do we create a new doc in the cldf folder?

**Comment by xrotwang** [comment]
I'd include both subsets. Time alignment should be modelled as
transparently as possible, I.e. in a way that could become part of the CLDF
standard.
AFAICT, time alignment is always relative to a soundfile. So we could have
a dedicated mediaReference property, and then a timeSlice property -
presumably using a Duration datatype.
If we don't mark availability of time alignment in the metadata, a null in
this column would then be sufficient to distinguish core and extended data.

Frederic Blum ***@***.***> schrieb am Do., 25. Aug. 2022,
08:55:

**Comment by FredericBlum** [comment]
I would go for another approach: The information whether a file is part of the extended set is marked in the metadata of files. So we could just retrieve the information from there. It is always true that `Extended == no time alignment", so I think it would be too complicated to code anything additionally.

**Comment by FredericBlum** [comment]
This would be part of the MediaTable as in #8 , correct?

**Comment by xrotwang** [comment]
I'm a bit lost trying to find the extended data. On http://concat.huma-num.fr/languages/anal1239 the two links to download annotation files for "core" and "extended" are identical. So I'd guess they both would resolve to the zipped contents of https://nakala.fr/10.34847/nkl.0dbazp8m
In this package, there's just one "*_metadata.csv" - and it only lists 10 different speakers, **not** the 15 speakers to be expected for the extended data. So how do we get at extended (meta)data at all?

**Comment by FredericBlum** [comment]
I am quite sure there is an error for Anal. If you check the [main page](http://concat.huma-num.fr/languages), you see that if you switch between Extended and Core, the number of speakers and words changes for Anal, but not the number of texts. So there seems to be a misplaced link for the extended set, not adding the additional texts for the extended set, but still counting them for words and speakers. I will open an issue about this on their repository.

For the other datasets, this works without problem, and the links are not identical. So I guess we can still proceed with setting up the code.

**Comment by FredericBlum** [comment]
I opened the respective issue (https://github.com/DoReCo/doreco/issues/6) to fix this. All other links should work fine.

Do you think the info about extended/core within the `metadata.csv` for each file is sufficient?

**Comment by xrotwang** [comment]
We stick with the core data, since that comes with a lot more guarantees - such as consistent speaker annotations.
See
https://github.com/cldf-datasets/doreco/blob/ac227b3f466612ea64e7d0dca9d92182e2954a18/cldfbench_doreco.py#L2-L12
for details.
