### ISSUE TITLE
Map sources to languages

### ISSUE THREAD

**Issue by FredericBlum** [cldf-datasets/doreco#7]
The bibtex key is not part of any of the parsed tables, so we may need to link them ourselves. The easiest solution would be to add a column in the etc/languages file and map them myself-

**Comment by FredericBlum** [comment]
There was an easier solution: prefixing `doreco-` to the glottocode is equal to the bibtex string. However, the `sources.bib` is currently not added to the cldf folder.

Relevant code: https://github.com/cldf-datasets/doreco/blob/main/cldfbench_doreco.py#L21-L24

@xrotwang Could you point me to my mistake?

**Comment by xrotwang** [comment]
`pybtex.database.parse_string` simply parses the string `doreco_CITATIONS.bib` (i.e. does **not** read the file denoted by this string), doesn't find any entries, so there's nothing to add.
